const Local_URL = "http://localhost:3000";
export const login_API = "/api/login";
export const addClient_API = "/api/addClient";
export const getClient_API = "/api/getClient";
export const updateClient_API = "/api/updateClient";
export const deleteClient_API = "/api/deleteClient";
export const logout_API = "/api/logout";
export const addEntry_API = "/api/addEntry";
export const getEntry_API = "/api/getEntry?clientId=";
export const addClothType_API = "/api/addClothType";
export const getClothTypeList_API = "/api/getClothTypeList";
export const updateEntryStatus_API = "/api/updateEntryStatus";
export const updateEntry_API = "/api/updateEntry";